# Generated by Django 2.2.8 on 2019-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_thumbnail',
            field=models.CharField(default='blog-1.jpg', max_length=200),
        ),
    ]
