# Generated by Django 2.2.8 on 2019-12-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20191228_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip',
            field=models.CharField(default='localhost', max_length=200),
            preserve_default=False,
        ),
    ]
