# Generated by Django 2.2.8 on 2019-12-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
