# Generated by Django 2.2.8 on 2020-01-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200102_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_thumbnail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_path', to='pages.Image'),
            preserve_default=False,
        ),
    ]
